### ISSUE TITLE
Drop unused variables from destructuring assignments

### ISSUE THREAD

**Issue by thepheer** [fabiosantoscode/terser#105]
**Bug report or Feature request?**
Not sure.

I'm trying to minize my build as mush as possible so I have `math.js` file in my project which exports all of the `Math` methods and props and some of my own stuff as well. Any time I need to do math I import funcs/vars from this file. I use rollup for bundling so there's no weird webpack module wiring or anything like that, all the code gets concatenated to something like:

```js
// from math.js
const { abs, acos, acosh /* ...etc */ } = Math
const lerp = () => /* ... */
const clamp = () => /* ... */

// from main.js
console.log(sin(PI))
```

And it goes to terser right after that. I assumed terser would figure out which variables the folowing code uses and which doesn't, so they can be dropped away safely. Turned out I was wrong, terser keeps all of them. I had some time trying to guess the right config options (like pure_funcs, pure_getters) but none of them seem to do the job. Especially on a code which has a destructuring assignment.

So I don't really know if this is the intended behavior or a bug. If a bug then it's a bug report. If not, then I'd like to know (and have) a way to drop everything that has no actual use in my code.

Here I have a few reproducible tests with unused vars. I don't really care about the one which uses aliasing instead of destructuring, but I tried it just in case and it also produced unexpected (for me) result.

**Version (complete output of `terser -V`)**

```
$ node -v
v10.9.0

$ npx terser -V
terser 3.8.2
```

**Complete CLI command or `minify()` options used**
```js
const terser = require('terser')

const options = {
  ecma: 8,
  compress: {
    // this one seems to convert `Math.foo` to `Math` (huh?)
    pure_getters: true,

    // this one seems to do nothing
    pure_funcs: Object
      .getOwnPropertyNames(Math)
      .filter(prop => typeof Math[prop] === 'function')
      .map(prop => 'Math.' + prop)
  }
}

const test = code => {
  const wrapped = `(() => { ${code} })()`
  const result = terser.minify(wrapped, options)
  console.log(result.code)
}

test(`
  const PI  = Math.PI
  const cos = Math.cos
  const sin = Math.sin
  const min = Math.min // ←
  const max = Math.max // ←

  console.log(cos(PI))
  console.log(sin(PI))
`)

test(`               // ↓↓↓  ↓↓↓
  const { PI, cos, sin, min, max } = Math

  console.log(cos(PI))
  console.log(sin(PI))
`)
```

**`terser` output or error**
```js
                                         // ↓↓↓↓ ↓↓↓↓
(()=>{const o=Math.PI,t=Math.cos,a=Math.sin;Math,Math;console.log(t(o)),console.log(a(o))})();
(()=>{const{PI:o,cos:n,sin:s,min:c,max:l}=Math;console.log(n(o)),console.log(s(o))})();
                          // ↑↑↑↑↑ ↑↑↑↑↑
```

**Expected result**
```js
// At least:
(()=>{const o=Math.PI,t=Math.cos,a=Math.sin;console.log(t(o)),console.log(a(o))})();
(()=>{const{PI:o,cos:n,sin:s}=Math;console.log(n(o)),console.log(s(o))})();

// Ideally: (convert to a destructuring assignment)
(()=>{const{PI:o,cos:n,sin:s}=Math;console.log(n(o)),console.log(s(o))})();
(()=>{const{PI:o,cos:n,sin:s}=Math;console.log(n(o)),console.log(s(o))})();
```

**Comment by kzc** [comment]
FWIW, when I fed the `unsafe_destructuring.js` example into [Google Closure Compiler](https://closure-compiler.appspot.com/home) it generated incorrect code:

```js
function extract(a) {
  console.log(a.b);
}
extract({a:1, b:2});
extract({get a() {
  console.log("side effect");
  return "side effect";
}, b:4});
```
When run it produces the incorrect result:
```
2
4
```
It's possible that one of their compiler assumptions is to always assume that getters are side effect free. Both `terser` and `uglify-js` only make that assumption with `pure_getters`.

**Comment by kzc** [comment]
Come to think of it, a new `unsafe_destructuring` compress option would not be required as this proposed feature could be enabled with the already existing options `pure_getters` (not enabled by default) and `unused` (enabled by default).

**Comment by thepheer** [comment]
Thanks for the fast reply.

Yeah, I understand that getters can have side effects and removing them would break some code even though it should be an extremely rare case. I can't imagine a real world code which would call a getter and then do nothing with the returned value. If you ask me, I would even remove them by default. Of course I'm not suggesting you to do it (at least without a major version bump).

So destructuring assignments are not supported by `pure_getters` yet? This is why I could not tell for sure if this is a bug or not, because the actual feature seems to be already there but does only a half of its job even when there's no destructuring. So I was a bit confuzed what exactly I'm requesting here. I guess it's an improvement request of the existing feature then. 😅

**Comment by kzc** [comment]
Terser errs on the side of caution for its default settings. 

> does only a half of its job even when there's no destructuring

Refer to the documentation for the options `module`, `toplevel`, `unsafe` and `passes`.

**Comment by thepheer** [comment]
> module, toplevel

These have no use in my case I believe. I have just a single IIFE at the top level.

Not much said about `unsafe` in the docs. It does some strange transformations in the 1st test case indeed but unfortunately nothing works on the 2nd one.

**Comment by fabiosantoscode** [comment]
Good issue. I'll find some time to work on this this weekend or the next.

**Comment by kzc** [comment]
@fabiosantoscode I have a PR that's close to complete. Writing the test cases take 10 times longer than writing the optimization itself.

**Comment by fabiosantoscode** [comment]
Ok @kzc I'll wait for your PR :)

**Comment by thepheer** [comment]
Seems to be working on the test case and on a real project as well.
Great job, guys, keep it up! 👍
