### ISSUE TITLE
Online terser minifier?

### ISSUE THREAD

**Issue by xem** [fabiosantoscode/terser#106]
Hello,
I'd like to make an online Terser minifier, with just HTML + JS, similar to those that existed for uglifyjs/es, but I'm not sure where to start.
Can the JS files of your project be used in the browser, without using node/npm?
Would loading all the JS files in the lib folder be enough to replace "require('terser')" ?
Thanks!

**Comment by kzc** [comment]
Each Terser release creates [`dist/browser.bundle.js`](https://github.com/fabiosantoscode/terser/blob/aafbf32dc2234bd2c4d2a70f45d6cc0c43436cc1/package.json#L18) that can be pulled into a script tag. Or you can clone the repo and run `npm run prepublish` to create the bundle yourself. Alternatively you can grab the bundle from a CDN.

```html
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/terser@3.8.2/dist/browser.bundle.js"/></script>
  <script>
    function minify() {
      var code = document.getElementById("code").value;
      var result = Terser.minify(code, {
        // toplevel: true,
        compress: {
          passes: 3,
        },
        output: {
          //beautify: true,
        },
      });
      var out = document.getElementById("out");
      if (result.error) {
          out.value = JSON.stringify(result.error, null, 2);
      } else {
          out.value = result.code;
      }
    }
  </script>
</head>
<body>
  <textarea id="code" rows="10" cols="30">
// ecmascript
(function(x, y) {
    const message = (text) => {
        console.log(text);
    }
    message(`Hello ES${x + y}`);
})(5, 1);
  </textarea>
  <br>
  <input type="button" id="ok" value="Minify" onclick="minify()" />
  <br>
  <textarea id="out" rows="10" cols="30"></textarea>
</body>
</html>
```
This information should probably go in the README. Pull request welcome.

**Comment by xem** [comment]
Thanks a lot!
In the meantime I managed to make a bundle.js file using browserify but your solution is even simpler.
Still sorting out what options I'm supposed to use to have the best possible ES6 compression (is "{toplevel:true, compress: {passes: 3}}" enough? do I have to add another option to enhance compression?), then I'll suggest an edit in the readme indeed!
Cheers

**Comment by kzc** [comment]
If you want to use `Terser.minify` in the browser with `sourceMap` support you'll have to use a bundler like `browserify` or `webpack` in order to get the `require("source-map")` references in `dist/browser.bundle.js` resolved.

If you want to explore more aggressive optimization options see `unsafe` and `pure_getters` - mind you, they will not necessarily work with all code. Consult the README. Every option is well documented.

**Comment by xem** [comment]
Thanks! I'll make all these options commented and editable in a separate textarea, like uglifyjs-online did :) 
![image](https://user-images.githubusercontent.com/1225909/45436947-36873800-b6b4-11e8-9aec-ceff4155d30f.png)

**Comment by xem** [comment]
Here's a first demo: https://xem.github.io/terser-online
Thanks for your help!
