### ISSUE TITLE
Support mangle.keep_fargs

### ISSUE THREAD

**Issue by eight04** [fabiosantoscode/terser#107]
**Bug report or Feature request?**

Feature request.

**Version (complete output of `terser -V`)**

terser 3.8.2

**Complete CLI command or `minify()` options used**

**`terser` input**

```js
const terser = require("terser");
console.log(terser.minify(`
function test(foo, bar, baz) {
  console.log(foo, bar, baz);
}
`, {mangle: {keep_fargs: true}}));
```

**Expected result**
```
function test(foo,bar,baz){console.log(foo,bar,baz)}
```

In some libraries, they use `fn.toString` to inspect argument names. In this case, we have to exclude function arguments from being mangled. See also: https://github.com/openstyles/stylus-lang-bundle/issues/3

**Comment by kzc** [comment]
This will not be supported. See Terser Compiler Assumptions:

- The code doesn't expect the contents of `Function.prototype.toString()` or
  `Error.prototype.stack` to be anything in particular.

https://github.com/fabiosantoscode/terser#compiler-assumptions

To achieve the effect you're looking for, disable `mangle` altogether.

**Comment by fabiosantoscode** [comment]
Agreed. Also glad to know you fixed it in your project in another way.
