### ISSUE TITLE
Question: Do we need to run the performance timings on every test?

### ISSUE THREAD

**Issue by fabiosantoscode** [fabiosantoscode/terser#30]
It sure does take an awful lot of time!

@kzc what do you think?

**Comment by kzc** [comment]
Do you mean running `test/benchmark.js` and `test/jetstream.js` upon each commit? Yes, I think they ought to be run each time. They occasionally find outright bugs. Even though it takes upwards of 45 minutes to run on Travis CI, it's automated so it's not a big deal. If it were manual then no one would remember to run it.

**Comment by fabiosantoscode** [comment]
Could we possibly run them in another CI? They won't find errors in separate node versions, right?

**Comment by kzc** [comment]
> They won't find errors in separate node versions, right?

One can't be certain about that. Bugs have been found in them before. The unit tests do not have complete coverage despite our best efforts. Not only are `test/benchmark.js` and `test/jetstream.js` perf tests, but they are actual representative real sized complex programs.

I don't understand what's the harm in running them for PRs and commits. No one is waiting for them. When you run "npm test" locally they are not run and it only takes 2 minutes.

Side note - the unit test coverage for ES6+ features is really lacking. Particularly with `expect_stdout` testing under various minify options. Could use a few hundred more test cases and a real world complex ES6+ application with an automated test suite.

**Comment by kzc** [comment]
Closing as answered.
