### ISSUE TITLE
Remove old uglify link in the top

### ISSUE THREAD

**Issue by TrySound** [fabiosantoscode/terser#32]
**Bug report or feature request?**
feature

**Version (complete output of `uglifyjs -V`)**
current

**ECMAScript input**

**Complete CLI command or `minify()` options used**

**Output or error**

**Expected result**

**Comment by kzc** [comment]
I was trying to figure out where the tagline at the top of https://github.com/fabiosantoscode/terser is configured:

**JavaScript parser / mangler / compressor / beautifier toolkit http://lisperator.net/uglifyjs/**

It's not in `package.json`. Only the repo owner @fabiosantoscode can change the top repo tagline via the **Edit** button to the right of the tagline within the github GUI.

@fabiosantoscode Could you please remove the lisperator link and update the github repo's tagline to:

```
JavaScript parser, mangler, optimizer and beautifier toolkit for ES6+
```

**Comment by fabiosantoscode** [comment]
Done @kzc . Thank you :)
