### ISSUE TITLE
A (reserved) named import throws an unexpected token error

### ISSUE THREAD

**Issue by psirenny** [fabiosantoscode/terser#36]
**Bug report or Feature request?**

Bug report

**Version (complete output of `terser -V`)**

3.7.5

**Complete CLI command or `minify()` options used**

`terser --compress -- input.js`

**`terser` input**

```
import { extends } from 'rollupPluginBabelHelpers';

var create = (opts => extends({
  isa: 'PBXBuildFile',
  fileRef_comment: ' '
}, opts));

export default create;
```

**`terser` output or error**

```
ERROR: Unexpected token: keyword (extends)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/psirenny/.nvm/versions/node/v10.1.0/lib/node_modules/terser/tools/node.js:21:1), <anonymous>:75:23)
    at fatal (/Users/psirenny/.nvm/versions/node/v10.1.0/lib/node_modules/terser/bin/uglifyjs:303:53)
    at run (/Users/psirenny/.nvm/versions/node/v10.1.0/lib/node_modules/terser/bin/uglifyjs:242:9)
    at Object.<anonymous> (/Users/psirenny/.nvm/versions/node/v10.1.0/lib/node_modules/terser/bin/uglifyjs:171:5)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
```

**Expected result**

```
import{extends}from"rollupPluginBabelHelpers";var create=opts=>extends({isa:"PBXBuildFile",fileRef_comment:" "},opts);export default create;
```

It seems that using a named import that matches a reserved keyword will throw an error. I'm not sure if this is expected behavior; however, I don't think it is. If I rename "extends" to something else, then it executes as expected.

**Comment by Conduitry** [comment]
I think this is expected behavior. Using a reserved name in an import is not the same as using it as an object key. `extends` is not a valid identifier, and so it is not a valid ES6 module export or import, as both require an identifier called `extends`. (So if `rollupPluginBabelHelpers` is exporting `extends`, then I imagine it would have to be doing so as e.g. a CommonJS export, not an ES6 one.)

**Comment by TrySound** [comment]
@psirenny The problem is `external` rollup option. If you want to ignore `node_modules` use this one
```js
const external = id => !id.startsWith('\0') && !id.startsWith('.') && !id.startsWith('/');
```
or just use babel runtime instead.

**Comment by kzc** [comment]
`acorn@5.5.3` reports the same error.

```
$ echo 'import { extends } from "baz";' | acorn --module
Unexpected keyword 'extends' (1:9)
```

**Comment by psirenny** [comment]
Wow, thanks for the quick response everyone.

> The problem is external rollup option. If you want to ignore node_modules use this one

My `external` function more or less works similarly. However, I'm confused because I think the function you proposed would treat `rollupPluginBabelHelpers` as external. I think this would be problematic because that module doesn't actually exist.

> or just use babel runtime instead.

Yea, I think I'm going to go that route.

**Comment by TrySound** [comment]
@psirenny `rollupPluginBabelHelpers`  has `\0` special char in the beginning which is considered with my `external` function. If it doesn't work try to upgrade `rollup-plugin-babel`.

**Comment by psirenny** [comment]
Aha! That clarifies my confusion completely. Thanks for the response @TrySound.
