### ISSUE TITLE
function.toString() is giving different results on optimized code

### ISSUE THREAD

**Issue by Flamefire** [fabiosantoscode/terser#52]
The issue is pretty simple:

`(function foo(){var a=1; return a;}).toString()` gets changed into `""+(function foo(){return 1;})` or even simply `"function(){}"` in upstream UglifyJS2 after this commit: https://github.com/mishoo/UglifyJS2/commit/70474310f3ba7f2f4395117ad2d779ced016075b

This is breaking code and there seems to be no intention to change that in upstream: https://github.com/mishoo/UglifyJS2/issues/3180

Are you interested in fixing this?

Background: I'm working on a deobfuscator which should not minify code but make it more readable which involves removing pointless (constant or unused) code. This is similar enough to base this work on UglifyJS/terser/esmangle. Techniques like the function.toString() are used very often to detect code changes.

**Comment by kzc** [comment]
I agree with @alexlamsl in that there's nothing to fix. The minifier assumptions are clearly stated in the documentation. Also, `unsafe` is not enabled by default for a reason - it makes additional assumptions about the code.

**Comment by kzc** [comment]
Google Closure and babel-minify make the same assumptions and produce similar results. By definition minifying code will necessarily alter functions.

FWIW, Terser did not merge https://github.com/mishoo/UglifyJS2/commit/70474310f3ba7f2f4395117ad2d779ced016075b as it appears to only benefit fuzzing.

**Comment by Flamefire** [comment]
You are right, they both produce the same as terser. UglifyJS is even worse as it returns "garbage", while terser returns the actual function representation (after minification that is)

While I understand that the motivation behind this is basically `We cannot optimize functions where toString  is used on` I find it sad, that all optimizers are fine with concluding `so don't use toString` instead of not optimizing such functions. I would have treated this the same as evaluation of functions with side-effects: Simply don't.   
The information where `toString` is used on is available to the compiler, the same as whether an expression is a side-effect-free constant but is not used. Same for Function.prototype.arguments which causes problems in other code too: https://blickly.github.io/closure-compiler-issues/#253

Side note: Just wanted to point out that not merging https://github.com/mishoo/UglifyJS2/commit/70474310f3ba7f2f4395117ad2d779ced016075b can have negative impact on code size because `this.node.print_to_string()` is pretty much always longer than `""+<this.node>` so it is not selected later (as described in https://github.com/mishoo/UglifyJS2/issues/3180) which inhibits further optimizations. Untested example: `/bar/.test(function(){return 1;}.toString())` which UglifyJS would reduce to `!1` and terser to `/bar/.test(""+function(){return 1})`. IMO the constant expression evaluation is flawed in general as longer, temporary results prevent shorter final results.

**Comment by kzc** [comment]
> IMO the constant expression evaluation is flawed in general as longer, temporary results prevent shorter final results.

Tests have shown otherwise. The generated code is optimized for gzip size. This has been hashed over a dozen or more times in various uglify issues. See output size versus gzip size: https://github.com/fabiosantoscode/terser#terser-fast-minify-mode
