### ISSUE TITLE
issue with replacement of arguments[x] when parameter is redefined

### ISSUE THREAD

**Issue by phazei** [fabiosantoscode/terser#58]
**Bug report**

**Version (complete output of `terser -V`)**
terser 3.7.6

**Complete CLI command or `minify()` options used**
Options:
uglify({ mangle: false, compress: { unused: false, drop_debugger:false } })

**`terser` input**

```
"use strict";
function test(data) {
    console.log("================");
    console.log("data/args0:", data, arguments[0]);
    if (typeof data !== "object") {
        data = {};
        console.log("data/args0:", data, arguments[0]);
        arguments[0] && (data.first = arguments[0]);
        arguments[1] && (data.second = arguments[1]);
        console.log("data/args0:", data, arguments[0]);
    }

}
test();
test('first','second');
```
expected output:
```
$ node test.js
================
data/args0: undefined undefined
data/args0: {} undefined
data/args0: {} undefined
================
data/args0: first first
data/args0: {} first
data/args0: { first: 'first', second: 'second' } first
```

**`terser` output or error**
```
"use strict";function test(data){console.log("================"),console.log("data/args0:",data,data),"object"!=typeof data&&(data={},console.log("data/args0:",data,data),data&&(data.first=data),arguments[1]&&(data.second=arguments[1]),console.log("data/args0:",data,data))}test(),test("first","second");
```
incorrect output:
```
$ node test.js 
================
data/args0: undefined undefined
data/args0: {} {}
data/args0: { first: [Circular] } { first: [Circular] }
================
data/args0: first first
data/args0: {} {}
data/args0: { first: [Circular], second: 'second' } { first: [Circular], second: 'second' }
```

I'm aware of the compression `arguments` option to "replace arguments[index] with function parameter name whenever possible".  I believe this is a case where it's not possible.  Should it be able to detect that and determine if it should replace the 'arguments[0]' ?

**Comment by kzc** [comment]
@phazei Cannot reproduce. Could you add one or more `console.log()` statements to your example to demonstrate the program producing a different result when minified?

**Comment by kzc** [comment]
Here's a different test case that produces an incorrect result when minified:

```
$ bin/uglifyjs -V
terser 3.7.6
```
```
$ cat issue-t58.js 
function f(x){
    console.log(x, arguments[0]);
    x = 2;
    console.log(x, arguments[0]);
    arguments[0] = 3;
    console.log(x, arguments[0]);
}
f();
f(1);
```
expected:
```
$ cat issue-t58.js | node
undefined undefined
2 undefined
2 3
1 1
2 2
3 3
```
actual:
```
$ cat issue-t58.js | bin/uglifyjs -bc | node
undefined undefined
2 2
2 2
1 1
2 2
3 3
```
Bug workaround - disable the `arguments` compress option:
```
$ cat issue-t58.js | bin/uglifyjs -bc arguments=false | node
undefined undefined
2 undefined
2 3
1 1
2 2
3 3
```
We may elect to have the `arguments` option disabled in `terser` by default as well.

I'd still like to see the example in the top post altered to produce incorrect output when run in the event that it is a different issue.

**Comment by kzc** [comment]
@phazei Thanks for the repro.

**Comment by kzc** [comment]
`uglify-js` has the same problem. Reported upstream: https://github.com/mishoo/UglifyJS2/issues/3192
