### ISSUE TITLE
Grunt plugin

### ISSUE THREAD

**Issue by acarstoiu** [fabiosantoscode/terser#59]
**Bug report or Feature request?**
Feature request

**Version (complete output of `terser -V`)**
any

**Complete CLI command or `minify()` options used**
not applicable

Can we have a Grunt plugin that uses _terser_? Apparently, it should be a copy of _grunt-contrib-uglify-es_ with a different uglifier module. The [Gulp plugin](https://www.npmjs.com/package/gulp-uglify-es) has already switched to _terser_.
Thanks.

**Comment by kzc** [comment]
Out of scope for this project.

Feel free to create and publish such a `terser` wrapper library.

**Comment by acarstoiu** [comment]
The problem is that I'm not willing to become a public person, nor to maintain it. If such a plugin is created, are you people willing to take ownership?

**Comment by kzc** [comment]
> If such a plugin is created, are you people willing to take ownership?

Of course not.

Workaround - use `yarn` instead of `npm`:

https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn
