### ISSUE TITLE
Order of yields changed in generator

### ISSUE THREAD

**Issue by XuluWarrior** [fabiosantoscode/terser#60]
**Bug report**

**Version 3.7.6**

**Complete CLI command**
`npx terser --compress -- test.js`

**`terser` input**
```
function* test() {
  const val1 = yield 1;
  yield 2;
  return val1;
}
```

**`terser` output**
*(Whitespace added)*
```
function* test() {
  return yield 2, yield 1
}
```

**Expected result**
Not sure how it should be compressed but `yield 1` should occur before `yield 2`

**Comment by kzc** [comment]
Bug workaround: disable the compress option `collapse_vars`.

```js
$ cat issue-t60.js
function* t() {
    const v = yield 1;
    yield 2;
    return v;
}
var g = t();
console.log(g.next().value, g.next().value);
```
```
$ cat issue-t60.js | node
1 2
```
```
$ cat issue-t60.js | bin/uglifyjs -c | node
2 1
```
```
$ cat issue-t60.js | bin/uglifyjs -c collapse_vars=false | node
1 2
```

**Comment by XuluWarrior** [comment]
That fixes our issue. Thanks for that.

Any chance you can make a new npm release so that we can integrate into our build? (terser is a sub-dependency and so it is problematic trying to force the use of a git commit)
