### ISSUE TITLE
`join_vars` bug: hoisting property defining class into object literal containing base

### ISSUE THREAD

**Issue by GHLover** [fabiosantoscode/terser#64]
**Bug report or Feature request?**

Definitely a bug. Failure to create correct code

**Version (complete output of `terser -V`)**

3.7.6

**Complete CLI command or `minify()` options used**

terser --mangle --compress  -- ./input.js
terser --mangle --compress --mangle-props -- ./input.js 

**`terser` input**
var Foo = {
    meth: function() {
        return 'something';
    }
}

Foo.Base = class {
    constructor() {
        this.prop = 'yes';
        this.id = 'dude';
    }
}

Foo._test = class extends Foo.Base {
    constructor() {
        super();
        this._dog = 'cat';
        this._count = 0;
    }
    alert() {
        this._count++;
        alert('yes');
    }
}
var test = new Foo._test();
test.alert();
alert(test.id);

**`terser` output or error**

TypeError: Foo is undefined

**Expected result**

An alert box that says "yes" and then one that says "dude"

**Comment by kzc** [comment]
Disable `join_vars` as a workaround.

```js
$ cat t64.js 
var Foo = {};
Foo.Base = class {
    constructor() {
        this.id = "PASS";
    }
};
Foo.Test = class extends Foo.Base {
    constructor() {
        super();
        console.log(this.id);
    }
};
new Foo.Test;
```
expected:
```
$ cat t64.js | node
PASS
```
actual:
```
$ cat t64.js | bin/uglifyjs -c | node
[stdin]:1
var Foo={Base:class{constructor(){this.id="PASS"}},Test:class extends Foo.Base{constructor(){super(),console.log(this.id)}}};new Foo.Test;
                                                                         ^
TypeError: Cannot read property 'Base' of undefined
```
workaround:
```
$ cat t64.js | bin/uglifyjs -c join_vars=false | node
PASS
```
