### ISSUE TITLE
AST_RegExp.value.raw_source incorrect

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/terser#67]
**Bug report or Feature request?**

bug introduced in fafc6993a968580388db508842ea093c9ab1bbfb

**Version (complete output of `terser -V`)**

post terser 3.7.6: fafc6993a968580388db508842ea093c9ab1bbfb

**Complete CLI command or `minify()` options used**

actual (after fafc6993a968580388db508842ea093c9ab1bbfb):

```
$ echo '/rx/ig' | bin/uglifyjs -o ast
{
  "_class": "AST_Toplevel",
  "body": [
    {
      "_class": "AST_SimpleStatement",
      "body": {
        "_class": "AST_RegExp",
        "value": {
          "raw_source": "rx"
        }
      }
    }
  ]
}
```

expected (before fafc6993a968580388db508842ea093c9ab1bbfb):

```
$ echo '/rx/ig' | bin/uglifyjs -o ast
{
  "_class": "AST_Toplevel",
  "body": [
    {
      "_class": "AST_SimpleStatement",
      "body": {
        "_class": "AST_RegExp",
        "value": {
          "raw_source": "/rx/ig"
        }
      }
    }
  ]
}
```

**Comment by kzc** [comment]
@fabiosantoscode Can https://github.com/fabiosantoscode/terser/commit/fafc6993a968580388db508842ea093c9ab1bbfb please be reverted?

This is difficult to get right.

**Comment by kzc** [comment]
When this bug is fixed the following patch can be applied to prevent future regressions:

```patch
--- a/test/mocha/minify.js
+++ b/test/mocha/minify.js
@@ -441,6 +441,20 @@ describe("minify", function() {
         assert.strictEqual(Uglify.minify(code, options).code, 'if(true)console.log(3);');
     });
 
+    describe("AST_RegExp", function() {
+        it("should preserve raw_source", function() {
+            var result = Uglify.minify("console.log(/\\/rx\\//ig);", {
+                output: {
+                    ast: true,
+                    code: true,
+                }
+            });
+            assert.strictEqual(result.code, "console.log(/\\/rx\\//gi);");
+            assert.strictEqual(result.ast.body[0].body.args[0].TYPE, "RegExp");
+            assert.strictEqual(result.ast.body[0].body.args[0].value.raw_source, "/\\/rx\\//ig");
+        });
+    });
+
     describe("enclose", function() {
         var code = read("test/input/enclose/input.js");
         it("Should work with true", function() {
```

**Comment by kzc** [comment]
Upstream is also wrong. I use this functionality to debug the Terser AST. 
```
$ bin/uglifyjs -V
uglify-js 3.4.1
```
```
$ echo '/rx/ig' | bin/uglifyjs -o ast
{
  "_class": "AST_Toplevel",
  "body": [
    {
      "_class": "AST_SimpleStatement",
      "body": {
        "_class": "AST_RegExp",
        "value": {
          "raw_source": "rx"
        }
      }
    }
  ]
}
```
I already fixed a similar Terser bug in spidermonkey AST in fa55c3c8b03eee355bb075c7289a304b3fca0599. 

Would you object to me reverting https://github.com/fabiosantoscode/terser/commit/fafc6993a968580388db508842ea093c9ab1bbfb?

**Comment by kzc** [comment]
> Check the upstream, you'll find that raw_source also doesn't include the wrapping slashes.

The slashes being omitted are just one of the bugs. Notice that the RegExp flags `ig` are also missing.

**Comment by fabiosantoscode** [comment]
> Notice that the RegExp flags ig are also missing.

What you can't see with `-o ast` is that the "value" object is a regular expression (not a plain object as the output would suggest), which has a "flags" property and that's what the flags are read from in the codebase.

> I already fixed a similar Terser bug in spidermonkey AST in fa55c3c.

This commit reintroduces an issue where extra backslashes would be introduced depending on the node version, because node would be put in charge of formatting regexen.

Check this out:

```
λ nvm use 6.14.3                                                                           
Now using node v6.14.3 (64-bit)                                                            
λ node                                                                                     
> /[\\/]/.toString()                                                                       
'/[\\\\/]/'                                                                                
>                                                                                          
λ nvm use 10.4.1                                                                           
Now using node v10.4.1 (64-bit)                                                            
λ node                                                                                     
> /[\\/]/.toString()                                                                       
'/[\\\\\\/]/'                                                                              
>                                                                                         
```

I agree that what we have is not too clean, but at least it's aligned with upstream:

 - AST_RegExp has a "value" property with a RegExp object
 - That RegExp object has a raw_source property with the contents of the regex (no slashes)
 - That RegExp object comes with a "flags" property which we read to get the flags
 - AST_RegExp's "raw" field is left unused

> Would you object to me reverting fafc699?

I don't want to open up a can of bugs, so probably reverting is the best option. However, long-term deviations from the upstream code cost us time in cherry-picking. Do you still think it's best to revert it?

**Comment by kzc** [comment]
> What you can't see with -o ast is that the "value" object is a regular expression (not a plain object as the output would suggest), which has a "flags" property and that's what the flags are read from in the codebase.

I often use `-o ast` to debug minify issues that arise. I need to dump the native AST in a human readable text form so it is easily understood. Because there's no standard for native Uglify/Terser AST it can be whatever form we deem it to be as long as it represents the data correctly and succinctly. Current master loses that functionality.

> This commit reintroduces an issue where extra backslashes would be introduced depending on the node version, because node would be put in charge of formatting regexen.

I think the priority should be correctness first and efficiency second. Having a regex that's a character longer is not a serious issue in my opinion. I objected to the original patch for reasons of potential breakage, and those concerns have unfortunately proved to be true with https://github.com/fabiosantoscode/terser/commit/7a10728a551504ac0fba279ab19769f9a2461837 and https://github.com/fabiosantoscode/terser/commit/fafc6993a968580388db508842ea093c9ab1bbfb. Regexes are a minefield of potential problems (unpaired surrogates anyone?) and this is why regex formatting is best left to the underlying JS engine.

> I don't want to open up a can of bugs, so probably reverting is the best option. However, long-term deviations from the upstream code cost us time in cherry-picking. Do you still think it's best to revert it?

I still think reverting https://github.com/fabiosantoscode/terser/commit/fafc6993a968580388db508842ea093c9ab1bbfb is the best option. Then the [test above](https://github.com/fabiosantoscode/terser/issues/67#issuecomment-399805372) can be merged to prevent future regressions. 

Almost every cherry-picked PR touching `lib/compress.js` is manually merged anyway, so the code divergence has already happened depending on the feature.  And even then those ES5 fixes have to be manually changed and new tests added to address ES6+ breakage that arises as was the case with a few recent upstream bug fixes. Fixing these ES6+ bugs was ultimately the reason behind the Terser fork.

**Comment by fabiosantoscode** [comment]
Ok, it makes sense to revert it.
