### ISSUE TITLE
TS types for the public API

### ISSUE THREAD

**Issue by manucorporat** [fabiosantoscode/terser#79]
We at [Stencil](https://stenciljs.com/) are looking to migrate from uglify-es to terser and i want to say thank you for this great open source effort!

I was wondering if there are any plans to add typing information (typescript) to the terser API.

I am not suggesting to port the existing .JS to .TS but rather provide a set of interfaces so tenser can be consumed programatically in a much safer and self-documented way (noticed that in IDEs like vscode, even if users are using JS, typing information is used to provide API autocompletion and a bunch of other things!)

It would also be great if the types are provided in the same package, so there is not need to "install" a secondary `@types/terser` package.

Would a PR adding types be merged? I would be happy to work on it and make a contribution to this incredible project.

Thanks for your time!

**Comment by kzc** [comment]
Terser only supports standard ECMAScript. By accepting JSX or TypeScript syntax it's a slippery slope towards maintaining non-standard features. There is a risk of ECMAScript grammar breakage if TypeScript syntax is introduced. It would also slow down ES parsing. Nevermind the TS language extensions (enums for example) - we don't want to get into the business of being a TS/JSX to ES transpiler.

But if you do create such a Terser fork and publish it yourself it can easily be dropped into existing projects with the [`yarn` `resolutions` mechanism](https://github.com/fabiosantoscode/terser#replacing-uglify-es-with-terser-in-a-project-using-yarn).

**Comment by Conduitry** [comment]
@kzc I don't think @manucorporat is talking about transpiling or porting anything - I believe this ticket is just to provide a `types.d.ts` file that describes terser's API, which consuming projects can use for type inference.

**Comment by kibertoad** [comment]
@kzc Here is an example of typings inside a 100% standard ECMAScript project :)
https://github.com/kibertoad/objection-find-query/blob/master/index.d.ts

**Comment by kzc** [comment]
> provide a types.d.ts file that describes terser's API

My mistake. If that's the case and it does not interfere with the existing Terser ES5 codebase in any way, then such a PR would be considered. Mind you, as the Terser minify API is extended and altered it is an additional maintenance burden.

**Comment by JordiAnderl** [comment]
I took the liberty and [typed terser](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/terser).
