### ISSUE TITLE
6a60eeac78 disables all reminify testing

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/terser#85]
**Bug report or Feature request?**

bug

**Version (complete output of `terser -V`)**

6a60eeac78b34

**Complete CLI command or `minify()` options used**

Apply this patch to latest master and observe no test failures with `npm test`:

```patch
--- a/test/ufuzz.json
+++ b/test/ufuzz.json
@@ -20,6 +20,7 @@
     },
     {
         "compress": {
+            "this_should_cause_test_to_error_out": true,
             "passes": 1e6,
             "unsafe": true
         },
```

When the same patch is applied to 8129b9a396437f9ad09e99ae8c3a1caf99407977 and `npm test` is run, it fails correctly:

```
*** Entering [compress]
--- arguments.js
    Running test [replace_index]
!!! failed input reminify
---INPUT---
{
    var arguments = [];
    console.log(arguments[0]);
    (function() {
        console.log(arguments[1], arguments["1"], arguments["foo"]);
    })("bar", 42);
    (function(a, b) {
        console.log(arguments[1], arguments["1"], arguments["foo"]);
    })("bar", 42);
    (function(arguments) {
        console.log(arguments[1], arguments["1"], arguments["foo"]);
    })("bar", 42);
    (function() {
        var arguments;
        console.log(arguments[1], arguments["1"], arguments["foo"]);
    })("bar", 42);
}
--ERROR---
DefaultsError: `this_should_cause_test_to_error_out` is not a supported option
```

@fabiosantoscode Please revert 6a60eeac78b34. It could break other aspects of Terser or its testing for all we know. 

I am very leary of these large sweeping patches in general. They always break something.

To be honest, the `preserve_line` option is completely useless and if it is broken then it should be removed from Terser.

**Comment by fabiosantoscode** [comment]
I applied this patch only because it makes the lines in expect_warnings relative to the start of the test case and not the file.

I'll see if I can apply only that feature and leave the rest alone.

**Comment by kzc** [comment]
`preserve_line` historically never worked correctly and is a questionable feature that few (if any) could have used. Although I'd prefer removing `preserve_line` support altogether, either a few line change to `test/run-tests.js` is needed for the test AST line fixups or just convert `test/compress/preserve_line.js` to a mocha test. 

As I step away from this project I just want to reiterate that Terser is an independent fork that was created as result of similar upstream patches constantly breaking `uglify-es`. Evaluate each new feature (whether upstream or user contributed PR) on its merits and if it doesn't benefit the majority of Terser users or risks introducing instability, then don't feel compelled to add it just for upstream option parity. Likewise, if some marginal or obsolete features like `ie8` support introduces a maintenance burden then they should be dropped in order to keep the project lean, focused and stable.

It's your call. I wish you and this project continued success.

**Comment by kzc** [comment]
@fabiosantoscode Thanks for the kind words.

Some parting advice for Terser maintenance:

* Always try to include an `expect_stdout` clause in new tests. This way it can take advantage of reminify testing. The exception to this is async test cases as `test/run-tests.js` can only handle synchronous code.
* Don't apply any upstream `ie8` patches. For whatever reason Terser is not affected by recently reported upstream `ie8` bugs and can run their test cases correctly as is. Even if `ie8` support were broken in Terser it is not worth fixing as it is obsolete and can potentially break ES code minified with or without `--ie8`.
* Do test each new upstream test case before applying any code fix as the code may already work correctly in Terser - even if the code generated is slightly different or is suboptimal. Feel free to merge such passing tests cases without changes to `lib/*.js`. If the test code generated is different in the `expect` or `expect_exact` clauses, just drop that expect clause and `expect_stdout` will work without it. That way it'll prevent a possible future regression.

**Comment by kzc** [comment]
@fabiosantoscode I think it would also be prudent to avoid merging any upstream legacy webkit or safari 9 bug fix or cleanup for the same reasons given for ie8. There is no upside to it.
