### ISSUE TITLE
uglify-es is no longer supported?

### ISSUE THREAD

**Issue by jhabdas** [fabiosantoscode/terser#90]
Saw this in the Terser readme:

> `uglify-es` is no longer maintained and `uglify-js` does not support ES6+.

Maybe I missed some big news but do please link to it because:

![terser-claim](https://user-images.githubusercontent.com/440298/43560342-90e26210-9644-11e8-91a2-e56b76428e46.png)

**Comment by TrySound** [comment]
Yeah, that would be better.

**Comment by edmorley** [comment]
> Maybe I should make it not a fork? 

Another advantage of this is that GitHub only indexes non-forks for code search etc. 

I believe GitHub support are happy to unlink a fork if desired.. :-)
