### ISSUE TITLE
`defaults` option isn't working as expected

### ISSUE THREAD

**Issue by matatk** [fabiosantoscode/terser#92]
**Bug report or Feature request?**

Bug report.

I'm working on a web browser extension that I want to run through terser for dead code removal, but making no other changes, as the extension needs to be reviewable by people, so it must not be mangled/minified.

However, `defaults` in the mangler isn't working as I expected.

**Version (complete output of `terser -V`)**

terser 3.8.1

**`terser` input**

file: code.js
```javascript
switch (ENV) {
	case 'firefox':
		console.log('Firefox')
		break
	case 'chrome':
		console.log('Chrome')
		break
	default:
		throw Error(`Unkown environment ${ENV}`)
}
```

file: without-defaults.json
```json
{
  "mangle": false,
  "compress": {
    "dead_code": true,
    "global_defs": {
      "ENV": "chrome"
    }
  },
  "output": {
    "beautify": true
  }
}
```

file: with-defaults.json
```json
{
  "mangle": false,
  "compress": {
    "defaults": false,
    "dead_code": true,
    "global_defs": {
      "ENV": "chrome"
    }
  },
  "output": {
    "beautify": true
  }
}
```

(This config is based on <https://github.com/mishoo/UglifyJS2/issues/2282>, which I gather was implemented in terser.)

**`terser` output or error**

When I run `terser --config-file without-defaults.json code.js` the output is

```javascript
console.log("Chrome");
```

When I run `terser --config-file with-defaults.json code.js` the output is

```javascript
switch ("chrome") {
  case "firefox":
    console.log("Firefox");
    break;

  case "chrome":
    console.log("Chrome");
    break;

  default:
    throw Error(`Unkown environment ${"chrome"}`);
}
```

**Expected result**

I expected to get the same result both times.

Whilst this test case produces the output I wanted without using `defaults`, it doesn't work in the context of the more complex code I'm trying to process. The `defaults` option sounds like it will do everything I need, as I just want to remove dead code, but it doesn't seem to work as expected.

I did also try setting `unused` to true, but it didn't make any difference.

Thanks for your work on terser :-).

**Comment by kzc** [comment]
> (This config is based on mishoo#2282, which I gather was implemented in terser.)

That example is not valid. 

Default `compress` functionality is spread across many options. You have to experiment enabling compress options one by one until it works.

```
$ terser code.js -c defaults=false,dead_code,evaluate,side_effects,switches,unused --define ENV='"chrome"' -b
console.log("Chrome");
```

If you're using `globals_defs`, you will likely need more default compress options in real life code. The `defaults` option was primarily designed for debugging Terser.

**Comment by kzc** [comment]
Working as designed. This issue can be closed.

**Comment by matatk** [comment]
Thanks @kzc for your quick and helpful reply. Seems I'd misunderstood the intent behind the `defaults` option; oops. It's working well with the settings you suggested.

In case this turns out to be helpful to anyone in future, I'm using these `compress` options (as above):

 * `defaults`
 * `dead_code`
 * `evaluate`
 * `side_effects` (originally I removed this because, from reading the docs, it didn't sound relevant, but leaving it out causes the constants from `case` statements within `switch` blocks to remain in the output code—had a look at terser's source and think I'm starting to grok this; glad @kzc suggested it.)
 * `switches`
 * `unused`

and these `output` options:

 * `beautify`
 * `braces` (I felt this would ensure it's very clearly readable to the extension's reviewers)
 * `comments`

The following seem like they may be relevant in future/I need to check terser's source to appreciate how they're handled (which I'm sure is properly, but I'd like to learn more :-)).

 * `keep_quoted_props`
 * `quote_style`
