### ISSUE TITLE
Do not rename ES imports if they are short enough

### ISSUE THREAD

**Issue by manucorporat** [fabiosantoscode/terser#96]
We have noticed this output:
```
const{h:t}=window.Ionic;import{a as e}from"./chunk-f7b6af08.js";
```
using latest version of terser.

Notice in both cases the exported properties are already one character.

I would expect:
```
const{h}=window.Ionic;import{a}from"./chunk-f7b6af08.js";
```

Unless there is some kind of name collision, terser should not emit extra code to rename props, otherwise, i guess the renaming is required.

**Comment by kzc** [comment]
Are you deploying code with import/export? JS bundlers typically replace them.

> terser should not emit extra code to rename props

That heuristic would not necessarily lead to shorter code in larger programs as longer names that are more frequently used could better employ a short alias. Plus once you factor in gzip all bets are off. It's not uncommon for slightly larger minified programs with a better frequency distribution of characters to produce smaller gzip output - [case in point](https://github.com/fabiosantoscode/terser#terser-fast-minify-mode).

Side note: in the off chance `mangle` happens to create a variable of the same name as the property in destructuring you'd benefit from setting the `ecma` output option to 6. The default is 5.

```
$ echo 'let {b} = obj;' | terser -mc --toplevel
let{b:b}=obj;

$ echo 'let {b} = obj;' | terser -mc --toplevel --ecma 6
let{b}=obj;
```

**Comment by manucorporat** [comment]
> Are you deploying code with import/export? 

yes, at (https://stenciljs.com/) our building architecture emits components with two targets:
 - native ESM+ES2015 for modern browsers
 - ES5 with AMD for legacy platforms.

>That heuristic would not necessarily lead to shorter code in larger programs as longer names that are more frequently used could better employ a short alias. 

That's very interesting and smart, thanks for the information

>Side note: in the off chance mangle happens to create a variable of the same name as the property in destructuring you'd benefit from setting the ecma output option to 6. The default is 5.

We will run some experiments with `--ecma`

Thanks for the response, I am closing the issue now :)
